name: Actualizar Leaderboard Real

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Ejecutar Extractor Blockchain
        run: node extractor.js

      - name: Guardar cambios en GitHub
        run: |
          git config --global user.name 'Leaderboard Bot'
          git config --global user.email 'bot@github.com'
          git add holders.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Actualización automática Top 100 Real" && git push)
          
